- hosts: all
  gather_facts: false
  become: yes

  vars:
    http_port: 80
    domain: www.Your-Domain.com

  tasks:
    - name: Add PHP Repository
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Update apt-get
      apt:
        update_cache: yes

    - name: Install all needed packages
      apt:
        name:
          [
            "make",
            "lsb-release",
            "ca-certificates",
            "apt-transport-https",
            "software-properties-common",
            "git",
            "zip",
            "unzip",
            "apache2",
            "python3",
            "mysql-server",
            "php7.3",
            "php7.3-curl",
            "php7.3-mbstring",
            "php7.3-bcmath",
            "php7.3-mysql",
            "php7.3-xml",
            "php7.3-gd",
            "php7.3-zip",
            "php7.3-pdo",
            "nodejs",
            "npm",
          ]
        state: present

    - name: create virtual host file
      template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf

    - name: a2ensite {{ domain }}
      command: a2ensite {{ domain }}

    - name: a2dissite 000-default.conf
      command: a2dissite 000-default.conf

    - name: Download and install Composer
      shell: curl -sS https://getcomposer.org/installer | php
      args:
        chdir: /usr/src/
        creates: /usr/local/bin/composer
        warn: false
      become: yes

    - name: Add Composer to global path
      copy:
        dest: /usr/local/bin/composer
        group: root
        mode: "0755"
        owner: root
        src: /usr/src/composer.phar
        remote_src: yes
      become: yes

    - name: add config mysql
      shell: echo "create database development" | mysql;echo "CREATE USER 'development'@'localhost' IDENTIFIED BY 'development'" | mysql;echo "GRANT ALL PRIVILEGES ON development.* TO 'development'@'localhost';" | mysql;echo "flush privileges" | mysql;

    - name: Create project Document Root
      file: path=/var/www/html/{{ domain }}/public state=directory

    - name: Enable rewrite module
      apache2_module:
        name: rewrite
        state: present
        ignore_configcheck: true

    - name: restart apache
      service:
        name: apache2
        state: restarted
